### ISSUE TITLE
Why aren't double, int, bool and string properties of AEXMLElement optionals?

### ISSUE THREAD

**Issue by mattsson** [tadija/AEXML#105]
Let's say I've created an `AEXMLElement` object from API data and I assume its value is a double but I'm obviously not sure, since it's coming from an external source. 

If I then use the `AEXMLElement` object's `double` property, I have no way of knowing if the data was invalid, I will just get `0.0` if it's invalid, but that may be valid data. Why isn't `double` an optional, so I can check if it's actually valid? As far as I can see I would have to check if `value` is non-nil and can be cast to `Double` myself.

**Comment by tadija** [comment]
Well, I thought those are like convenience properties which you can use in most cases to accomplish your logic. If you would need more specific behavior you could extend `AEXMLElement` and implement other computable properties with your logic. Now, I agree it could be vise-versa too.

**Comment by mattsson** [comment]
Hmm, I'm not sure I understand your logic. Could you give me an example of a scenario, where I would expect or even want to get a `0.0` value when that isn't the actual value from the XML source?

This is Apple's introduction of optionals:

> You use optionals in situations where a value may be absent. An optional represents two possibilities: Either there _is_ a value, and you can unwrap the optional to access that value, or there _isn’t_ a value at all.

It seems to me like this is a perfect scenario for using optionals.

**Comment by tadija** [comment]
Yes, that's why `value` property **is** optional. You may achieve your logic by just using that property and casting it to different types yourself. You may also extend `AEXMLElement` to have properties like `optionalDouble`, `optionalBool` etc. if you want to use it like that everywhere. 

While I understand your reasoning behind this, try to understand that those are **convenience** properties for more simple usage of the library and I have 2 reasons not to change that:

1. Simplicity - you probably noticed that `subscript` of `AEXMLElement` could also return optional (if element is not found) but it doesn't. That's because if everything would be optional it would make end-user's code more verbose and harder to write in the end. Some other libraries prefer this approach, but I think that's exactly what differentiate `AEXML` from the others.

2. Legacy - even if I would _maybe_ do it like you said if I was making this from scratch (still maybe not because of reason 1.), think about breaking changes of existing end user's code if this kind of logic update is introduced. It would require handling those optionals everywhere in code, and I bet most of the users would handle it the same way as it's already working now.

About scenario in which this approach could work as supposed: imagine a backend which always returns exactly the same structure of data which always contains all the fields in proper format, so that way "alternative" values would never be used, and end user's code would be more brief and easier to write.

**Comment by mattsson** [comment]
How do you know the backend always returns valid data? I'm not trying to be facetious here, but using a remote API seems like one of the most obvious scenarios where you should properly validate the received data, since you have no control over what the API returns.

I don't find your arguments very convincing, breaking changes are expected with major or minor releases, I mean, every major new Swift version usually has a bunch of breaking changes. I think you're opting for minor added convenience in place of important data validation, but it's obviously your library and therefore your decision, and I don't seem to be able to convince you otherwise. :)

**Comment by tadija** [comment]
I don't know if backend will always work properly (probably not), that was just "example"... :) 

Anyway, in the end, this is kind of everybody's code, feel free to contribute by implementing those changes and making a pull request.

After all this discussion, I think that compromise would be to add new separate properties (rather then replacing existing), and leave existing convenience properties as they are. This way users of library could choose what they prefer to use and we don't have breaking changes. We just need to think of some good explanatory names for those new properties. What do you think?

**Comment by mattsson** [comment]
I think that's a fine compromise. I added a suggestion in #110.

**Comment by tadija** [comment]
Hi @mattsson,

I thought some more about this and decided to make initial convenience typed accessors to be optionals (instead of having default values) like you suggested on the beginning of this issue.

I just didn't like redundancy which came up in #110 that much, so even if this is gonna be a breaking change for some, it will be easy to fix and it makes more sense in the end.

Cheers

**Comment by mattsson** [comment]
@tadija I am very happy to hear that, will look forward to the release!

**Comment by tadija** [comment]
@mattsson release is already there (4.1.0) :)

**Comment by mattsson** [comment]
Ah, nice. I took a look at the code. You left the non-optional `string` in there?

**Comment by tadija** [comment]
Yes, because it's used for other accessors, and `value` is already optional string so no need to duplicate that.
