### ISSUE TITLE
Build on linux fails

### ISSUE THREAD

**Issue by egorzhdan** [tadija/AEXML#106]
When I build & run a project on macOS it works fine, but on Linux it doesn't compile and shows lots of errors like this:

```
<...>/AEXML-4.0.2/Sources/Parser.swift:71:16: error: method cannot be marked @objc because the type of the parameter 1 cannot be represented in Objective-C
    @objc func parser(_ parser: XMLParser,

<...>/AEXML-4.0.2/Sources/Parser.swift:82:16: error: method cannot be marked @objc because the type of the parameter 2 cannot be represented in Objective-C
    @objc func parser(_ parser: XMLParser, foundCharacters string: String) {
```

Swift version is 3.0.1 and OS is ubuntu14.04 on Travis-CI. The package is added via Swift PM.

**Comment by wallstead** [comment]
I'm getting the same errors.

**Comment by tadija** [comment]
Hi @egorzhdan and @wallstead, thanks for reporting.

In the latest version (4.1.0) I removed all `@objc` flags (those were required earlier, but not anymore) so that might be a fix for this.

I'll close this issue now, but If you find time please confirm if it's fixed or reopen issue if not.

Cheers
