### ISSUE TITLE
Can read operations return nilable AEXMLElement?

### ISSUE THREAD

**Issue by dmcgloin** [tadija/AEXML#13]
First, very cool work. Love the simple and super-easy API. Great job!

Perhaps I've not yet appreciated the finer points of Swift, but I'm wondering if the subscript, and last functions/properties can return nilable AEXMLElement (i.e. AEXMLElement?) ?

For my use case, I don't know if a server's XML response will have certain elements. I want to access them if they are present.

Right now, it appears when I do something like this:

     let errorDetail = xmlDocument!.rootElement["errorDetail"]

...I get a dummy empty AEXMLElement, but I really just want nil in this case.

Again, thanks for the great work!

**Comment by tadija** [comment]
Hello, thanks for the feedback.

Subscript is intentionally made to be non-optional because of the cleaner code when using AEXML (so you don't have to type a lot of ? or ! when searching for a nested element).

Though said, I just pushed a new version where properties `all` and `last` are indeed optional from now,
and there's also a new property `first` which does same as the subscript, but returns optional.

So in your example you could use it like this:
`if let errorDetail = xmlDocument!.root["errorDetail"].first {
}`

Cheers,
// T
