### ISSUE TITLE
XML Attribute Order

### ISSUE THREAD

**Issue by daveanderson** [tadija/AEXML#148]
According to the XML spec

> the order of attribute specifications in a start-tag or empty-element tag is not significant

however the variable order of the attributes causes unnecessary differences each time that AEXML outputs data.

In order to minimize unnecessary difference it would be nice if the attributes not in a non-deterministic order.

**Comment by muthukrishnanOCS** [comment]
I had the same issue

**Comment by muthukrishnanOCS** [comment]
@tadija , Do you have solution for this order issue?

**Comment by benstahl** [comment]
I sort of made a solution for this by customizing the code. It's admittedly hackish but does work for the intended purpose (keeping attribute order), although it's not tested extensively. What I did was to make an array property for AEXMLElement that keeps track of the attribute keys (strings). There's a convenience initializer that adds each string into the array before passing the attribute dictionary on to the designated initializer. Then when outputting the XML string, if loops over the ordered key array we saved and uses that as the key to fetch the value from the attributes dictionary. Because we're looping over the ordered array instead of the unordered dictionary keys, the original order is preserved. If the ordered key dictionary is empty, it simply does it the standard way by using the attribute dictionary keys.

Declare property (AEXMLElement):
```
/// Array that retains the order of the attribute keys added.
open var attrKeyOrder = [String]()
```

Convenience init that parses the dictionary keys and stores them in an ordered array (AEXMLElement):
```
public convenience init(name: String, value: String? = nil, orderedAttributes: KeyValuePairs<String, String>) {
    self.init(name: name, value: value, attributes: [:])

    for oa in orderedAttributes {
        self.attrKeyOrder.append(oa.key)
        attributes[oa.key] = oa.value
    }
}
```

Change to "xml" computed String property (AEXMLElement) to use the ordered keys if present:
```
// insert attributes
if attrKeyOrder.isEmpty == false {
    for orderedKey in attrKeyOrder {
        if let noptValue = attributes[orderedKey] {
            xml += " \(orderedKey)=\"\(noptValue.xmlEscaped)\""
        }
    }
} else {
    for (key, value) in attributes {
        xml += " \(key)=\"\(value.xmlEscaped)\""
    }
}
```

Note that for this to work, you _must_  use the convenience initializer (setting attributes individually will mess up this system) and pre-populate an array of type KeyValuePairs. Example:
```
let xmlDoc = AEXMLElement(name: "xml", value: nil, attributes: ["encoding" : "utf-8", "standalone" : "yes"])

let rootAttrs: KeyValuePairs = [
    "a": "1",
    "b": "2",
    "c": "3"
]

let rootElem = AEXMLElement(name: "myElem", orderedAttributes: rootAttrs)

xmlDoc.addChild(rootElem)

print(xml) // Should yield the line <myElem a="1" b="2" c="3" /> where the order of the keys is known and consistent.
```

**Comment by tadija** [comment]
I kind of fixed this by simply sorting attributes by their key, so at least the output shall always be the same now.
