### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by ardavydov** [tadija/AEXML#182]
Can you update this library to support Apple Silicon? Currently I have to use Xcode via Rosetta just because of this library 🙂 Much thanks for the great pod btw!

**Comment by tadija** [comment]
hi @ardavydov i am not sure why do you have this issue or what exactly is the issue that you're having?

this project still builds without any errors using current xcode (14.0.1) on apple sillicon machine, so that's why i'm confused.

could you please elaborate why do you have to use rosetta because of this lib? what happens if you don't?

**Comment by ardavydov** [comment]
Thanks for the answer! When i try to build a project with AEXML on M1 i get 
`Could not find module 'AEXML' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator`

Build Active Architecture to No doesn't help, so i have to use xCode via Rosetta

**Comment by tadija** [comment]
is it feasible for you to create a blank example project which is reproducing this same issue?

how do you manage dependencies, via cocoapods?

**Comment by ardavydov** [comment]
Nvm, it was an internal issues. Thank anyway for you help!
