### ISSUE TITLE
Carthage error

### ISSUE THREAD

**Issue by Domsware** [tadija/AEXML#74]
Trying to update AEXML using Carthage lead to an error:
```
A shell task (/usr/bin/xcrun xcodebuild -project someDir/Carthage/Checkouts/AEXML/AEXML.xcodeproj -scheme AEXMLExample -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:  
xcodebuild: error: Scheme AEXMLExample is not currently configured for the build action.
```

Carthage version : 0.16.2
Xcode : 7.3.1

**Comment by Domsware** [comment]
Removing scheme for `AEXMLExample` solve the problem. But this is only a trick and a solution must be found for this error.

**Comment by tadija** [comment]
I'm not sure how Carthage tried to build that scheme (it's from Demo project) instead of those from Framework project... Anyway, I didn't have that kind of problems when testing it earlier, and now with coming of Swift Package Manager... Well it's not that much of a priority, so I'll just close this one. Feel free to send a pull request if you make some fix for Carthage!
